### ISSUE TITLE
PS Crashes

### ISSUE THREAD

**Issue by bryjonez** [loxia01/PSInternetConnectionSharing#3]
Hi @loxia01,

I need to share a VPN connection with a network adapter:  FAH_VPN shared to VoipPhone

![image](https://github.com/loxia01/PSInternetConnectionSharing/assets/91334170/a5038b11-915d-4cb6-b9f8-631fd0ebd3dc)

However when I issue the command:

`Set-Ics -PublicConnectionName "FAH_VPN" -PrivateConnectionName "VoipPhone" -PassThru`

Powershell crashes....

Any suggestions?

I can make the share manually and` Disable-Ics `works after manually setting it up.

Thanks
Bryan

**Comment by loxia01** [comment]
> Hi @loxia01,
> 
> I need to share a VPN connection with a network adapter: FAH_VPN shared to VoipPhone
> 
> ![image](https://user-images.githubusercontent.com/91334170/241063318-a5038b11-915d-4cb6-b9f8-631fd0ebd3dc.png)
> 
> However when I issue the command:
> 
> `Set-Ics -PublicConnectionName "FAH_VPN" -PrivateConnectionName "VoipPhone" -PassThru`
> 
> Powershell crashes....
> 
> Any suggestions?
> 
> I can make the share manually and`Disable-Ics`works after manually setting it up.
> 
> Thanks Bryan

Thanks for submitting. Are you on Windows 10 or 11? Have not tested this module on Windows 11.

**Comment by loxia01** [comment]
Edit: Updated the module to fix the bug. Probably the bug didn't cause your crash, but you can update the module and test.

I just discovered a small bug when doing some testing. It prevents `Set-ICS` to throw an error when the private network connection is disabled. Don't know if this caused the crash you reported, but to be sure you can just check if your network adapter is disabled before you run `Set-ICS`.

**Comment by loxia01** [comment]
Thanks for your message.

Unfortunately I cannot reproduce your problem on my Win 10 machine.
I know Microsoft did some sort of security update to ICS last month, but I am not sure if that is causing your crash.

Regards



23 nov. 2023 02:44 av ***@***.***:

**Comment by opzch** [comment]
I know that's off-topic here, but maybe this can be helpful for someone facing these issues: Something that's not immediately obvious that, instead of relying on Windows sharing methods, you can just install a proxy app on the main machine and set other devices to connect through its' port (if they support it, of course). Almost any application should be sufficient to route through your current connection, but in some cases if you also need to connect through other (Internet) proxies, you might consider installing a proxy manager like v2RayN or similar that supports multiple protocols. Far more reliable than this.
